// <auto-generated />
using System;
using HostelMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HostelMS.API.Migrations
{
    [DbContext(typeof(HostelDbContext))]
    partial class HostelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HostelMS.API.Models.ApplicationUser", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("longtext");
                b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<int>("Role").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("HostelMS.API.Models.Room", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Amenities").HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<int>("Capacity").HasColumnType("int");
                b.Property<string>("Floor").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<decimal>("MonthlyFee").HasColumnType("decimal(10,2)");
                b.Property<int>("OccupiedCount").HasColumnType("int");
                b.Property<string>("RoomNumber").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<int>("Type").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("Rooms");
            });

            modelBuilder.Entity("HostelMS.API.Models.Student", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Address").HasMaxLength(200).HasColumnType("varchar(200)");
                b.Property<string>("Department").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("GuardianName").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("GuardianPhone").HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<string>("GuardianRelation").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<DateTime>("JoiningDate").HasColumnType("datetime(6)");
                b.Property<DateTime?>("LeavingDate").HasColumnType("datetime(6)");
                b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<string>("ProfilePhoto").HasColumnType("longtext");
                b.Property<string>("QRCode").HasColumnType("longtext");
                b.Property<int?>("RoomId").HasColumnType("int");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("StudentId").IsRequired().HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<int?>("UserId").HasColumnType("int");
                b.Property<string>("Year").HasMaxLength(20).HasColumnType("varchar(20)");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("StudentId").IsUnique();
                b.HasIndex("RoomId");
                b.HasIndex("UserId").IsUnique();
                b.ToTable("Students");
            });
#pragma warning restore 612, 618
        }
    }
}
